parameters:
  database_user: 'root'
  database_name: 'mvc'
  database_host: 'localhost'
  database_password: ~
  uploads_dir: 'uploads'
  noreply_email: 'nporeply@mvc.com'
  some_api_key: '5csdcbe5d7gwhfclzhfu78'

routing:
  homepage:
    pattern: /mvc/
    controller: DefaultController
    action: indexAction

  books_list:
    pattern: /mvc/books
    controller: BookController
    action: indexAction

  feedback:
    pattern: /mvc/feedback
    controller: DefaultController
    action: feedbackAction

  sign_in:
    pattern: /mvc/sign-in
    controller: SecurityController
    action: loginAction

  logout:
    pattern: /mvc/logout
    controller: SecurityController
    action: logoutAction

  cart:
    pattern: /mvc/cart
    controller: CartController
    action: indexAction

  book_item:
    pattern: /mvc/book/{id}
    controller: BookController
    action: showAction
    parameters:
      id: '[0-9]+'

  admin_homepage:
    pattern: /mvc/admin
    controller: Admin\DefaultController
    action: indexAction

  admin_books:
    pattern: /mvc/admin/books
    controller: Admin\BookController
    action: indexAction
